use_frameworks!

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LLNetWork_Example' do
  pod 'LLNetWork', :path => '../'

  target 'LLNetWork_Tests' do
    inherit! :search_paths

    
  end
end
